-- MySQL Script generated by MySQL Workbench
-- Fri Jun 11 18:33:12 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema pnyees
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pnyees
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pnyees` DEFAULT CHARACTER SET utf8 ;
USE `pnyees` ;

-- -----------------------------------------------------
-- Table `pnyees`.`sistema`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pnyees`.`sistema` ;

CREATE TABLE IF NOT EXISTS `pnyees`.`sistema` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `valor` VARCHAR(45) NULL,
  `default` VARCHAR(45) NULL,
  `estado` ENUM('0', '1') NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pnyees`.`usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pnyees`.`usuarios` ;

CREATE TABLE IF NOT EXISTS `pnyees`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(45) NULL,
  `clave` VARCHAR(50) NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `telefono` INT NULL,
  `correo` VARCHAR(45) NULL,
  `estado` ENUM('0', '1') NULL,
  `fecha_registro` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pnyees`.`roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pnyees`.`roles` ;

CREATE TABLE IF NOT EXISTS `pnyees`.`roles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `estado` ENUM('0', '1') NULL,
  `roles_permisos_id` INT NOT NULL,
  PRIMARY KEY (`id`, `roles_permisos_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pnyees`.`admin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pnyees`.`admin` ;

CREATE TABLE IF NOT EXISTS `pnyees`.`admin` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(45) NULL,
  `clave` VARCHAR(50) NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `telefono` INT NULL,
  `correo` VARCHAR(45) NULL,
  `estado` ENUM('0', '1') NULL,
  `roles_id` INT NOT NULL,
  `roles_roles_permisos_id` INT NOT NULL,
  PRIMARY KEY (`id`, `roles_id`, `roles_roles_permisos_id`),
  CONSTRAINT `fk_admin_roles1`
    FOREIGN KEY (`roles_id` , `roles_roles_permisos_id`)
    REFERENCES `pnyees`.`roles` (`id` , `roles_permisos_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;



-- -----------------------------------------------------
-- Table `pnyees`.`usuarios_direcciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pnyees`.`usuarios_direcciones` ;

CREATE TABLE IF NOT EXISTS `pnyees`.`usuarios_direcciones` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `telefono` INT NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(100) NOT NULL,
  `usuarios_id` INT NOT NULL,
  PRIMARY KEY (`id`, `usuarios_id`),
  CONSTRAINT `fk_usuarios_direcciones_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `pnyees`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;



-- -----------------------------------------------------
-- Table `pnyees`.`compras`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pnyees`.`compras` ;

CREATE TABLE IF NOT EXISTS `pnyees`.`compras` (
  `id` INT NOT NULL,
  `total_compra` DECIMAL(10,2) NULL,
  `total_descuento` DECIMAL(10,2) NULL,
  `total_impuesto` DECIMAL(10,2) NULL,
  `metodo_pago` VARCHAR(45) NULL,
  `fecha_compra` DATETIME NULL,
  `estado_envio` ENUM('0', '1') NULL,
  `estado_proceso` ENUM('0', '1') NULL,
  `estado_aprobacion` ENUM('0', '1') NULL,
  `direccion` VARCHAR(45) NULL,
  `comprascol` VARCHAR(45) NULL,
  `usuarios_direcciones_id` INT NOT NULL,
  `usuarios_direcciones_usuarios_id` INT NOT NULL,
  PRIMARY KEY (`id`, `usuarios_direcciones_id`, `usuarios_direcciones_usuarios_id`),
  CONSTRAINT `fk_compras_usuarios_direcciones1`
    FOREIGN KEY (`usuarios_direcciones_id` , `usuarios_direcciones_usuarios_id`)
    REFERENCES `pnyees`.`usuarios_direcciones` (`id` , `usuarios_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;



-- -----------------------------------------------------
-- Table `pnyees`.`compras_detalles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pnyees`.`compras_detalles` ;

CREATE TABLE IF NOT EXISTS `pnyees`.`compras_detalles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `precio` DECIMAL(10,2) NULL,
  `impuesto` DECIMAL(10,2) NULL,
  `descuento` DECIMAL(10,2) NULL,
  `fecha` DATETIME NULL,
  `id_producto` INT NULL,
  `facturas_id` INT NOT NULL,
  PRIMARY KEY (`id`, `facturas_id`),
  CONSTRAINT `fk_facturas_detalles_facturas1`
    FOREIGN KEY (`facturas_id`)
    REFERENCES `pnyees`.`compras` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;



-- -----------------------------------------------------
-- Table `pnyees`.`ordenes_compras`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pnyees`.`ordenes_compras` ;

CREATE TABLE IF NOT EXISTS `pnyees`.`ordenes_compras` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `total_orden_compra` DECIMAL(10,2) NULL,
  `total_descuento` DECIMAL(10,2) NULL,
  `total_impuesto` DECIMAL(10,2) NULL,
  `metodo_pago` VARCHAR(45) NULL,
  `fecha` DATETIME NULL,
  `estado_proceso` ENUM('0', '1') NULL,
  `estado_aprobacion` ENUM('0', '1') NULL,
  `direccion` VARCHAR(45) NULL,
  `ordenes_comprascol` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pnyees`.`ordenes_compras_detalles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pnyees`.`ordenes_compras_detalles` ;

CREATE TABLE IF NOT EXISTS `pnyees`.`ordenes_compras_detalles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre_producto` VARCHAR(45) NULL,
  `precio_producto` DECIMAL(10,2) NULL,
  `impuesto_producto` DECIMAL(10,2) NULL,
  `descuento_producto` DECIMAL(10,2) NULL,
  `fecha` DATETIME NULL,
  `id_producto` INT NULL,
  `ordenes_compras_id` INT NOT NULL,
  `usuarios_direcciones_id` INT NOT NULL,
  `usuarios_direcciones_usuarios_id` INT NOT NULL,
  PRIMARY KEY (`id`, `ordenes_compras_id`, `usuarios_direcciones_id`, `usuarios_direcciones_usuarios_id`),
  CONSTRAINT `fk_ordenes_compras_detalles_ordenes_compras1`
    FOREIGN KEY (`ordenes_compras_id`)
    REFERENCES `pnyees`.`ordenes_compras` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ordenes_compras_detalles_usuarios_direcciones1`
    FOREIGN KEY (`usuarios_direcciones_id` , `usuarios_direcciones_usuarios_id`)
    REFERENCES `pnyees`.`usuarios_direcciones` (`id` , `usuarios_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;




-- -----------------------------------------------------
-- Table `pnyees`.`productos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pnyees`.`productos` ;

CREATE TABLE IF NOT EXISTS `pnyees`.`productos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `precio` DECIMAL(10,2) NULL,
  `impuesto` DECIMAL(10,2) NULL,
  `url_imagen` VARCHAR(50) NULL,
  `estado` ENUM('0', '1') NULL,
  `descripcion` VARCHAR(100) NULL,
  `fecha` DATETIME NULL,
  `facturas_detalles_id` INT NOT NULL,
  `facturas_detalles_facturas_id` INT NOT NULL,
  `ordenes_compras_detalles_id` INT NOT NULL,
  `ordenes_compras_detalles_ordenes_compras_id` INT NOT NULL,
  PRIMARY KEY (`id`, `facturas_detalles_id`, `facturas_detalles_facturas_id`, `ordenes_compras_detalles_id`, `ordenes_compras_detalles_ordenes_compras_id`),
  CONSTRAINT `fk_productos_facturas_detalles1`
    FOREIGN KEY (`facturas_detalles_id` , `facturas_detalles_facturas_id`)
    REFERENCES `pnyees`.`compras_detalles` (`id` , `facturas_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_productos_ordenes_compras_detalles1`
    FOREIGN KEY (`ordenes_compras_detalles_id` , `ordenes_compras_detalles_ordenes_compras_id`)
    REFERENCES `pnyees`.`ordenes_compras_detalles` (`id` , `ordenes_compras_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;




-- -----------------------------------------------------
-- Table `pnyees`.`roles_permisos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pnyees`.`roles_permisos` ;

CREATE TABLE IF NOT EXISTS `pnyees`.`roles_permisos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `editar` ENUM('0', '1') NULL,
  `crear` ENUM('0', '1') NULL,
  `ver` ENUM('0', '1') NULL,
  `eliminar` ENUM('0', '1') NULL,
  `roles_id` INT NOT NULL,
  `roles_roles_permisos_id` INT NOT NULL,
  PRIMARY KEY (`id`, `roles_id`, `roles_roles_permisos_id`),
  CONSTRAINT `fk_roles_permisos_roles1`
    FOREIGN KEY (`roles_id` , `roles_roles_permisos_id`)
    REFERENCES `pnyees`.`roles` (`id` , `roles_permisos_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;



-- -----------------------------------------------------
-- Table `pnyees`.`productos_descuento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pnyees`.`productos_descuento` ;

CREATE TABLE IF NOT EXISTS `pnyees`.`productos_descuento` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `descuento` DECIMAL(10,2) NULL,
  `estado` ENUM('0', '1') NULL,
  `maximo` DECIMAL(10,2) NULL,
  `minimo` DECIMAL(10,2) NULL,
  `productos_id` INT NOT NULL,
  PRIMARY KEY (`id`, `productos_id`),
  CONSTRAINT `fk_productos_descuento_productos1`
    FOREIGN KEY (`productos_id`)
    REFERENCES `pnyees`.`productos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;



-- -----------------------------------------------------
-- Table `pnyees`.`bancos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pnyees`.`bancos` ;

CREATE TABLE IF NOT EXISTS `pnyees`.`bancos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `tipo` ENUM('1', '2') NULL,
  `cuenta` VARCHAR(45) NULL,
  `estado` ENUM('0', '1') NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- CREATE INDEX `fk_admin_roles1_idx` ON `pnyees`.`admin` (`roles_id` ASC, `roles_roles_permisos_id` ASC) VISIBLE;
-- CREATE INDEX `fk_usuarios_direcciones_usuarios1_idx` ON `pnyees`.`usuarios_direcciones` (`usuarios_id` ASC) VISIBLE;
-- CREATE INDEX `fk_compras_usuarios_direcciones1_idx` ON `pnyees`.`compras` (`usuarios_direcciones_id` ASC, `usuarios_direcciones_usuarios_id` ASC) VISIBLE;
-- CREATE INDEX `fk_facturas_detalles_facturas1_idx` ON `pnyees`.`compras_detalles` (`facturas_id` ASC) VISIBLE;
-- CREATE INDEX `fk_ordenes_compras_detalles_ordenes_compras1_idx` ON `pnyees`.`ordenes_compras_detalles` (`ordenes_compras_id` ASC) VISIBLE;
-- CREATE INDEX `fk_ordenes_compras_detalles_usuarios_direcciones1_idx` ON `pnyees`.`ordenes_compras_detalles` (`usuarios_direcciones_id` ASC, `usuarios_direcciones_usuarios_id` ASC) VISIBLE;
-- CREATE INDEX `fk_productos_facturas_detalles1_idx` ON `pnyees`.`productos` (`facturas_detalles_id` ASC, `facturas_detalles_facturas_id` ASC) VISIBLE;
-- CREATE INDEX `fk_productos_ordenes_compras_detalles1_idx` ON `pnyees`.`productos` (`ordenes_compras_detalles_id` ASC, `ordenes_compras_detalles_ordenes_compras_id` ASC) VISIBLE;
-- CREATE INDEX `fk_roles_permisos_roles1_idx` ON `pnyees`.`roles_permisos` (`roles_id` ASC, `roles_roles_permisos_id` ASC) VISIBLE;
-- CREATE INDEX `fk_productos_descuento_productos1_idx` ON `pnyees`.`productos_descuento` (`productos_id` ASC) VISIBLE;


-- Ajustes en base de datos
ALTER TABLE `admin` CHANGE `clave` `clave` VARCHAR(100) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `usuarios` CHANGE `clave` `clave` VARCHAR(100) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `compras_detalles` ADD `cantidad` INT(11) NOT NULL AFTER `precio`;
ALTER TABLE `compras` ADD `id_usuario` INT NOT NULL AFTER `usuarios_direcciones_usuarios_id`;
ALTER TABLE `compras` ADD INDEX(`id_usuario`);
ALTER TABLE `ordenes_compras` ADD `id_usuario` INT(11) NOT NULL AFTER `ordenes_comprascol`;
ALTER TABLE `ordenes_compras` ADD INDEX(`id_usuario`);
ALTER TABLE `compras_detalles` CHANGE `facturas_id` `id_compra` INT(11) NOT NULL;
ALTER TABLE `compras` ADD `nro_compra` VARCHAR(20) NOT NULL AFTER `id`;

-- volcado de datos 
INSERT INTO `roles` (`id`, `nombre`, `estado`, `roles_permisos_id`) VALUES ('1', 'administrador', '1', '1');
INSERT INTO `roles_permisos` (`id`, `editar`, `crear`, `ver`, `eliminar`, `roles_id`, `roles_roles_permisos_id`) VALUES ('1', '1', '1', '1', '1', '1', '1');
INSERT INTO `admin` (`id`, `usuario`, `clave`, `nombre`, `telefono`, `correo`, `estado`, `roles_id`, `roles_roles_permisos_id`) VALUES ('1', 'root', '$2y$10$ZwJIPtUyfn4yefA1hKlI3.r.rBegXb3ZCfacQroBlz3miqpBtpQcK', 'system', '12345', 'system@mail.com', '1', '1', '1');